EZP-32164: Implemented IconPathResolver service
ezsystems/ezplatform-core pull request #24
Opened 2020-11-17 12:54 UTC by webhdx

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-32164](https://jira.ez.no/browse/EZP-32164)
| **Improvement**| no
| **New feature**    | yes
| **Target version** | `1.0`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

2020-11-17 14:15 UTC, alongosz requested changes
It should be quite quick to add simple unit test coverage for the implementation, just one method (with and without 2nd argument). Otherwise looks good.

CS remark:

2020-11-17 14:15 UTC, alongosz commented on src/IbexaPlatformAssetsBundle/lib/Resolver/IconPathResolverInterface.php
> +    public function resolve(string $icon, string $set = null): string;
```suggestion
    public function resolve(string $icon, ?string $set = null): string;
```

2020-11-17 15:04 UTC, webhdx commented
@alongosz Always feels great to remind yourself about your ol' good friend **unit tests**: d2efa7b

![image](https://user-images.githubusercontent.com/10212760/99406706-7ed2be00-28ee-11eb-88a0-cab21ac368c6.png)

2020-11-17 15:06 UTC, webhdx commented
Travis should be green in a minute

2020-11-18 09:01 UTC, alongosz approved these changes
Thx, I know it was a painful experience! ;) Looks good.
Minor CS:

2020-11-18 09:01 UTC, alongosz commented on tests/IbexaPlatformAssetsBundle/lib/Resolver/IconPathResolverTest.php
> +    public function resolveDataProvider()
```suggestion
    public function resolveDataProvider(): array
```

2020-11-18 09:04 UTC, webhdx commented on tests/IbexaPlatformAssetsBundle/lib/Resolver/IconPathResolverTest.php
> +    public function resolveDataProvider()
Fixed: 
557d922

2020-11-18 09:59 UTC, bogusez approved these changes

2020-11-18 10:18 UTC, merged