EZP-32214: Refactored config/packages/overrides/* as Compiler Passes
ezsystems/ezplatform-core pull request #25
Opened 2020-12-08 11:07 UTC by webhdx

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-32214](https://jira.ez.no/browse/EZP-32214)
| **New feature**    | yes
| **Target version** |`master`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

In order to make `config/packages/overrides/{platformsh.php,generic.php}` files work we had to update `src/AppKernel.php`. This is a problem for flex based applications as installing recipes doesn't allow to override existing files. This means on new installations we won't be able to use our configuration for P.sh, Cache, DFS etc. 

This was not a good solution from the beginning as we basically injected custom logic into configuration files. This should be handled by a Compiler Pass.

2020-12-08 11:52 UTC, alongosz requested changes

2020-12-08 11:52 UTC, alongosz commented on src/EzPlatformCoreBundle/bundle/DependencyInjection/Compiler/GenericConfigPass.php
> +        }
I think that for every available cache pool there has to be a config file, so if it's missing, there's clearly some mistake, right?
WDYT about improving DX and throwing config exception in such case?

2020-12-08 11:52 UTC, alongosz commented on src/EzPlatformCoreBundle/bundle/DependencyInjection/Compiler/GenericConfigPass.php
> +        }
I see a repetitive pattern here. This can be refactored into a loop over a parameter map.

2020-12-08 11:52 UTC, alongosz commented on src/EzPlatformCoreBundle/bundle/DependencyInjection/Compiler/PlatformShConfigPass.php
> +        }
Optionally what I would do here is split this into smaller task-related methods for: dfs, redis cache, solr, http cache.

2020-12-08 13:20 UTC, alongosz approved these changes

2020-12-09 09:46 UTC, webhdx commented
These are file copies from meta repository. All comments reported by @alongosz will be provided as a followup PR after beta release. Merging it as is.

2020-12-09 09:47 UTC, merged